package com.gmcoreui.utils

object Keys {
    const val PERMISSION_REQUEST_LOCATION = 101
    const val PERMISSION_REQUEST_SETTINGS = 102
    const val PERMISSION_REQUEST_PHONE_CALL = 103
    const val PERMISSION_REQUEST_CAMERA_STORAGE = 104
    const val PERMISSION_REQUEST_STORAGE = 105
    const val PERMISSION_REQUEST_CAMERA = 106
    const val PERMISSION_REQUEST_READ_SMS = 107
    const val PERMISSION_REQUEST_MICRO_PHONE = 108
    const val PERMISSION_REQUEST_PHONE_STATE = 109
}